version: '3'

networks:
  one:

services:
  numbergenerators:
    image: numbergenerators_api_mongo:latest
    container_name: api
    networks: 
    - one
    ports:
      - 7777:80
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks: 
    - one
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
     - influxdb_data:/var/lib/influxdb 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: SA
      MONGO_INITDB_ROOT_PASSWORD: Password12!
    networks:
    - one
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  sqlserver_data:
    external: true
  rabbitmq_data:
    external: true
  mongodb_data:
    external: true
  influxdb_data:
    external: true

