version: '3'

networks:
  test-environment:

services:
  numbergenerators:
    image: numbergenerators_api:latest
    container_name: api
    networks: 
    - test-environment
    ports:
      - 7777:80
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - test-environment
    volumes:
      - influxdb-volume:/var/lib/influxdb
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:latest
    networks: 
    - test-environment
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=SA
      - POSTGRES_PASSWORD=Password12!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: elasticsearch:7.17.0
    networks: 
    - test-environment
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always
  kibana:
    hostname: kibana
    image: kibana:7.17.0
    container_name: kibana
    networks: 
    - test-environment
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    volumes:
      - kibana_data:/usr/share/kibana/data
    restart: always
volumes:
  sqlserver_data:
  rabbitmq_data:
  elasticsearch_data:
  kibana_data:
  postgres_data:
  influxdb-volume:
    external: true


