version: '3'

networks:
  one:

services:
  numbergenerators:
    image: numbergenerators_api_postgres:latest
    container_name: api
    networks: 
    - one
    ports:
      - 7777:80
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks: 
    - one
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
     - influxdb_data:/var/lib/influxdb 
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:latest
    networks: 
    - one
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=SA
      - POSTGRES_PASSWORD=Password12!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  sqlserver_data:
    external: true
  rabbitmq_data:
    external: true
  postgres_data:
    external: true
  influxdb_data:
    external: true


